#!/bin/bash
set -euo pipefile

dotfiles () {
	git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME "$@"
}

cd "${HOME}"
dotfiles status
if [ "$?" -eq 0 ]; then
	echo "Dotfiles repository already initialised"
else
	git clone https://github.com/maruina/dotfiles
	mkdir -p $HOME/.dotfiles-backup
	dotfiles checkout
	if [ "$?" -ne 0 ]; then
		echo "Dotfiles installed.";
	else
	    echo "Backing up pre-existing dotfiles.";
	    dotfiles checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I {} mv {} .dotfiles-backup/{}
	fi
	dotfiles checkout
	dotfiles config status.showUntrackedFiles no
fi

grep -q -F 'alias dotfiles="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"' ~/.zshrc || echo 'alias dotfiles="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"' >> ~/.zshrc